title: NetTcp
description: Provide Tcp Server and Socket fully exposed to Qml.
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Olivier LDff
repo_url: "https://github.com/OlivierLDff/QOlm"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
